### ISSUE TITLE
Email receipt and notification

### ISSUE THREAD

**Issue by craigvalentine** [Esri/geoform-template-js#468] opened 2015-07-06 10:04 UTC
At East Dunbartonshire Council we currently use an ESRI product called LocalView Fusion. It is similar to ArcGIS Online in many respects. One of the templates we use is similar to GeoForm in that the user submits a form which can update a feature layer. One way in which it is more useful than GeoForm is there is an option to email the user a receipt and even better notify that a submission has been made via an email. It also can send an XML of the details of the submission. Without this feature you could easily miss a new submission.

**Comment by driskull** [comment] 2015-08-21 16:50
Hi @craigvalentine 
I think GeoEvent Extension for server would help with this.

http://www.esri.com/software/arcgis/arcgisserver/extensions/geoevent-extension

duplicate of #472

**Closed by driskull** 2015-08-21 16:50 UTC
